name: pigpio-nils
base: core20
version: git
summary: GPIO library
description: |
  pigpio is a library for the Raspberry which allows control of
  the General Purpose Input Outputs (GPIO).
  pigpio works on all versions of the Pi.

license: Unlicense
architectures:
 - armhf
grade: devel
confinement: strict

parts:
  pigpio:
    plugin: make
    source-type: git
    source: https://github.com/nils-bauer/pigpio.git
    build-packages:
      - gcc
      - make
      - libc6
      - python3-distutils-extra
  pigpiod-wrapper:
    plugin: dump
    source: .
      
apps:
  pigpiod:
    daemon: simple
    command: pigpiod_wrapper
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/local/lib
    plugs:
     - network-bind
     - physical-memory-control
layout:
  /var/pigpio.pid:
    bind-file: $SNAP_DATA/pigpio.pid
