name: pigpio-nils
base: core18 # the base snap is the execution environment for this snap
version: '0.1' 
summary: GPIO library
description: |
  pigpio is a library for the Raspberry which allows control of
  the General Purpose Input Outputs (GPIO).
  pigpio works on all versions of the Pi.

license: Unlicense
architectures:
 - armhf
grade: devel
confinement: strict

parts:
  pigpio:
    plugin: make
    # source-type: local
    # source: PIGPIO
    source-type: git
    source: https://github.com/joan2937/pigpio.git
    build-packages:
      - gcc
      - make
      - libc6
      - python3-distutils-extra
  pigpiod-wrapper:
    plugin: dump
    source: .
      
apps:
  pigpiod:
    daemon: simple
    command: pigpiod_wrapper
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib:$LD_LIBRARY_PATH
    plugs:
     - network
     - network-bind
     - physical-memory-control
layout:
  /var/run:
    type: tmpfs

